name: check_pr_body
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-body:
    runs-on: ubuntu-18.04
    env:
      GO111MODULE: on
      GOPATH: /tmp/gopath
      CONFORM: github.com/talos-systems/conform@v0.1.0-alpha.19
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Cache conform
        id: cache-conform
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-conform-${{ env.CONFORM }}
          path: ${{ env.GOPATH }}
          restore-keys: |
            ${{ runner.os }}-conform-
      - name: Get conform
        if: steps.cache-conform.outputs.cache-hit != 'true'
        run: go get $CONFORM
        # mkdir -p $GOPATH/bin; wget https://github.com/talos-systems/conform/releases/download/v0.1.0-alpha.19/conform-linux-amd64 -O $GOPATH/bin/conform; chmod +x $GOPATH/bin/conform
      - name: Check body
        run: |
          set -o pipefail
          python3 .github/extract_commit_message.py < ${{ github.event_path }} | tee /dev/stderr | $GOPATH/bin/conform enforce --commit-msg-file /dev/stdin
