name: test

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ secrets.GITHUB_TOKEN }} | base64
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 64
      - name: Log
        run: |
          BASH_XTRACEFD=1
          set -x
          echo base ${{ github.base_ref }}
          git remote -v
          git log --graph --all --decorate --oneline
          git fetch origin master
          git log --graph --all --decorate --oneline
          git log --graph --all --decorate --oneline origin/${{ github.base_ref }}..@
          echo number ${{ github.event.number }}
          echo merge sha ${{ github.event.pull_request.merge_commit_sha }}
          echo head sha ${{ github.event.pull_request.head.sha }}
          echo base sha ${{ github.event.pull_request.base.sha }}
          curl -H 'Authorization: token ${{ github.token }}' ${{ github.event.pull_request.commits_url }}
          cat ${{ github.event_path }}
